baseurl         = "https://kenopsia.ga"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Kenopsia"
  subtitle    = "Kenopsia"

  cover       = "uploads/images/top.jpg"
  description = "This is de awesome description"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "finalcraneo"
  fbName = "finalcraneo"
  # githubName = "finalcraneo"

  logo = "uploads/images/logo.png"
  orgName = "Kenopsia"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Joseph Flores"
  authorAvatar = "uploads/images/me.png"
  authorLocation = "Puebla, MX"
  authorWebsite = "https://finalcraneo.github.io"
  authorDescription = "Este soy yo"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Blog"
  url = "/tags/Blogs/"
  weight = 100

[[menu.main]]
  name = "Food"
  url = "/categories/food/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95